# Generated by Django 5.2.7 on 2025-10-27 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prediction', models.CharField(choices=[('Benign', 'Benign'), ('Malware', 'Malware')], max_length=20)),
                ('confidence', models.FloatField()),
                ('malware_probability', models.FloatField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10)),
                ('recommendation', models.CharField(max_length=50)),
                ('registry_read', models.IntegerField(default=0)),
                ('registry_write', models.IntegerField(default=0)),
                ('registry_delete', models.IntegerField(default=0)),
                ('network_threats', models.IntegerField(default=0)),
                ('processes_malicious', models.IntegerField(default=0)),
                ('files_malicious', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
